### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by iamcco** [NativeScript/capacitor#9]
I get many errors when run `yarn build:mobile`

![image](https://user-images.githubusercontent.com/5492542/130716007-67783523-27a2-4b6e-8f5b-f0aa25889f42.png)

I can build `yarn build:nativescript` but I can not build my web project any more. What should I do, please help

this is my project's dependencies

```
 "dependencies": {
    "cross-gesture": "^1.3.3",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "rxh": "^1.0.1",
    "rxjs": "^7.3.0",
    "@capacitor/android": "^3.2.0",
    "@capacitor/app": "^1.0.2",
    "@capacitor/cli": "^3.2.0",
    "@capacitor/core": "^3.2.0",
    "@capacitor/ios": "^3.2.0",
    "@capacitor/status-bar": "^1.0.2",
    "@capacitor/toast": "^1.0.2",
    "@nativescript/capacitor": "^1.0.0",
    "capacitor-plugin-filesharer": "^1.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.19",
    "@types/react-dom": "^17.0.9",
    "@typescript-eslint/eslint-plugin": "^4.29.3",
    "@typescript-eslint/parser": "^4.29.3",
    "@vitejs/plugin-react-refresh": "^1.3.5",
    "cordova-res": "^0.15.3",
    "eslint": "^7.31.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^7.0.1",
    "prettier": "^2.3.2",
    "typescript": "^4.3.5",
    "vite": "^2.5.0"
  }
```

**Comment by NathanWalker** [comment]
Hi @iamcco , is src/nativescript the only directory that contains NativeScript code or is it possible you have NativeScript code outside of that folder?

If possible to share project we can help look as well.

**Comment by iamcco** [comment]
In my web project I only import like this `import { native } from '@nativescript/capacitor';` and call the helper function `native.enablePencilTap` defined in `src/nativescript/utils`.

And I find an workaround is that set the `"skipLibCheck": true` in tsconfig.json. 

![image](https://user-images.githubusercontent.com/5492542/130725569-446b7642-eb39-4463-9c62-9d6b5c62b5ec.png)

**Comment by iamcco** [comment]
Close this since seems like only me have the issue, and the workaround that set the "skipLibCheck": true in tsconfig.json works for me.
